 

name: CI

on:
  push:
    branches: [ deploy ]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v2

      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build 
      
